// <auto-generated />
using System;
using MGO_MVC.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MGO_MVC.Migrations
{
    [DbContext(typeof(MGOContext))]
    partial class MGOContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MGO_MVC.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 283,
                            Name = "Backpacks"
                        },
                        new
                        {
                            CategoryId = 320,
                            Name = "Mountain Bikes"
                        },
                        new
                        {
                            CategoryId = 410,
                            Name = "Sleeping Bags"
                        },
                        new
                        {
                            CategoryId = 477,
                            Name = "Tents"
                        },
                        new
                        {
                            CategoryId = 685,
                            Name = "Downhill Ski Boots"
                        },
                        new
                        {
                            CategoryId = 729,
                            Name = "Downhill Skis"
                        });
                });

            modelBuilder.Entity("MGO_MVC.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZIP")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 11,
                            City = "Murfreesboro",
                            Email = "tlock1212@hotmail.com",
                            FirstName = "Todd",
                            LastName = "Lockard",
                            State = "TN",
                            Street1 = "5634 Furnace Hill Rd.",
                            ZIP = "37130"
                        },
                        new
                        {
                            CustomerId = 13,
                            City = "Gatlinburg",
                            Email = "drenee12@yahoo.com",
                            FirstName = "Renee",
                            LastName = "Devlin",
                            State = "TN",
                            Street1 = "739 Birch Ave.",
                            ZIP = "37138"
                        },
                        new
                        {
                            CustomerId = 15,
                            City = "Murfreesboro",
                            Email = "naturelover@rockbridge.net",
                            FirstName = "Justin",
                            LastName = "Knighton",
                            State = "TN",
                            Street1 = "513 Forest Ave.",
                            ZIP = "37128"
                        },
                        new
                        {
                            CustomerId = 20,
                            City = "Gatlinburg",
                            Email = "rockbridgeoutdoors@mail.net",
                            FirstName = "Rockbridge",
                            LastName = "Outdoors",
                            State = "TN",
                            Street1 = "8913 Stagecoach Rd.",
                            ZIP = "37738"
                        },
                        new
                        {
                            CustomerId = 23,
                            City = "Knoxville",
                            Email = "sherryfamily@mail.com",
                            FirstName = "Craig",
                            LastName = "Sherry",
                            State = "TN",
                            Street1 = "909 Cedar Ave.",
                            ZIP = "37918"
                        },
                        new
                        {
                            CustomerId = 25,
                            City = "Gatlinburg",
                            Email = "canoemaster@hotmail.com",
                            FirstName = "Jeff",
                            LastName = "Reichert",
                            State = "TN",
                            Street1 = "4398 Old Allegheny Cir.",
                            Street2 = "Apt. 8",
                            ZIP = "37138"
                        },
                        new
                        {
                            CustomerId = 27,
                            City = "Murfreesboro",
                            Email = "kathyware22@yahoo.com",
                            FirstName = "Kathryn",
                            LastName = "Ware",
                            State = "TN",
                            Street1 = "324 Fuller St.",
                            ZIP = "37128"
                        },
                        new
                        {
                            CustomerId = 30,
                            City = "Gatlinburg",
                            Email = "storminnorman@hotmail.com",
                            FirstName = "Norman",
                            LastName = "Hernandes",
                            State = "TN",
                            Street1 = "12 Sycamore Ave. 6",
                            ZIP = "37728"
                        },
                        new
                        {
                            CustomerId = 32,
                            City = "Gatlinburg",
                            Email = "masterhiker@hotmail.com",
                            FirstName = "Stanley",
                            LastName = "Calhoun",
                            State = "TN",
                            Street1 = "590 Gibbs St.",
                            ZIP = "37738"
                        },
                        new
                        {
                            CustomerId = 34,
                            City = "Cherokee",
                            Email = "aliciamoorehead121@aol.com",
                            FirstName = "Alicia",
                            LastName = "Moorehead",
                            State = "NC",
                            Street1 = "643 Summit St.",
                            ZIP = "37738"
                        },
                        new
                        {
                            CustomerId = 36,
                            City = "Knoxville",
                            Email = "lizhazelwood@aol.com",
                            FirstName = "Elizabeth",
                            LastName = "Hazelwood",
                            State = "TN",
                            Street1 = "897 Cypress Ave.",
                            ZIP = "37918"
                        },
                        new
                        {
                            CustomerId = 40,
                            City = "Asheville",
                            Email = "bridgetc@rockbridge.net",
                            FirstName = "Bridget",
                            LastName = "Crozier",
                            State = "NC",
                            Street1 = "601 Walker St.",
                            ZIP = "28715"
                        },
                        new
                        {
                            CustomerId = 41,
                            City = "Cherokee",
                            Email = "mgmt@grassrootsrec.com",
                            FirstName = "Grassroots",
                            LastName = "Recreation",
                            State = "NC",
                            Street1 = "16 Rockfish School Ln.",
                            ZIP = "28719"
                        },
                        new
                        {
                            CustomerId = 42,
                            City = "Gatlinburg",
                            Email = "mattmetz@gmail.com",
                            FirstName = "Matthew",
                            LastName = "Metz",
                            State = "TN",
                            Street1 = "2385 Mill St.",
                            ZIP = "37738"
                        },
                        new
                        {
                            CustomerId = 50,
                            City = "Cherokee",
                            Email = "appoutfitters@gmail.com",
                            FirstName = "Appalachian",
                            LastName = "Outfitters",
                            State = "NC",
                            Street1 = "9823 Whitehill Rd.",
                            Street2 = "Suite A",
                            ZIP = "37130"
                        },
                        new
                        {
                            CustomerId = 52,
                            City = "Ashville",
                            Email = "rogerfeliciano12@rockbridge.net",
                            FirstName = "Roger",
                            LastName = "Feliciano",
                            State = "NC",
                            Street1 = "8341 Maury River Rd.",
                            ZIP = "28732"
                        },
                        new
                        {
                            CustomerId = 55,
                            City = "Gatlinburg",
                            Email = "johnnylovesnature@gmail.com",
                            FirstName = "Johnny",
                            LastName = "Driggers",
                            State = "TN",
                            Street1 = "6783 Allegheny Dr.",
                            ZIP = "37738"
                        },
                        new
                        {
                            CustomerId = 57,
                            City = "Cherokee",
                            Email = "erniec53@live.com",
                            FirstName = "Ernest",
                            LastName = "Cochrane",
                            State = "NC",
                            Street1 = "9013 Main St.",
                            ZIP = "28719"
                        },
                        new
                        {
                            CustomerId = 58,
                            City = "Murfreesboro",
                            Email = "joshieb@mail.com",
                            FirstName = "Joshua",
                            LastName = "Botello",
                            State = "TN",
                            Street1 = "704 Peyton St.",
                            ZIP = "37128"
                        },
                        new
                        {
                            CustomerId = 60,
                            City = "Ashville",
                            Email = "tbradford3@mail.com",
                            FirstName = "Tiffany",
                            LastName = "Bradford",
                            State = "NC",
                            Street1 = "745 Davidson St.",
                            ZIP = "28715"
                        },
                        new
                        {
                            CustomerId = 61,
                            City = "Gatlinburg",
                            Email = "vigila23@hotmail.com",
                            FirstName = "Adam",
                            LastName = "Vigil",
                            State = "TN",
                            Street1 = "801 Chestnut Ave.",
                            ZIP = "37738"
                        },
                        new
                        {
                            CustomerId = 64,
                            City = "Knoxville",
                            Email = "management@brafting.com",
                            FirstName = "Blue",
                            LastName = "Ridge Rafting",
                            State = "TN",
                            Street1 = "17003 Crabtree Falls Hwy.",
                            ZIP = "37918"
                        },
                        new
                        {
                            CustomerId = 66,
                            City = "Cherokee",
                            Email = "bseals@rockbridge.net",
                            FirstName = "Bryan",
                            LastName = "Seals",
                            State = "NC",
                            Street1 = "17 W. McDowell St",
                            ZIP = "28719"
                        },
                        new
                        {
                            CustomerId = 69,
                            City = "Asheville",
                            Email = "mountainbiker12@hotmail.com",
                            FirstName = "Eugene",
                            LastName = "Nixon",
                            State = "NC",
                            Street1 = "901 Walnut Ave.",
                            ZIP = "38732"
                        },
                        new
                        {
                            CustomerId = 70,
                            City = "Gatlinburg",
                            Email = "hikeallday@rockbridge.net",
                            FirstName = "Sheryl",
                            LastName = "Vaught",
                            State = "TN",
                            Street1 = "316 Short St.",
                            Street2 = "Apt. 14",
                            ZIP = "37738"
                        },
                        new
                        {
                            CustomerId = 71,
                            City = "Asheville",
                            Email = "campingenthusiast@yahoo.com",
                            FirstName = "Tyler",
                            LastName = "Dominick",
                            State = "NC",
                            Street1 = "5490 Stillwater Dr.",
                            ZIP = "28732"
                        },
                        new
                        {
                            CustomerId = 74,
                            City = "Knoxville",
                            Email = "skifanatic@aol.com",
                            FirstName = "Kevin",
                            LastName = "Banner",
                            State = "TN",
                            Street1 = "400 W. Washington St.",
                            ZIP = "37918"
                        },
                        new
                        {
                            CustomerId = 75,
                            City = "Knoxville",
                            Email = "luismatt20@gmail.com",
                            FirstName = "Matthew",
                            LastName = "Luis",
                            State = "TN",
                            Street1 = "7523 Palace Hill Ln.",
                            ZIP = "37918"
                        },
                        new
                        {
                            CustomerId = 78,
                            City = "Asheville",
                            Email = "richeyfamily@yahoo.com",
                            FirstName = "Victoria",
                            LastName = "Richey",
                            State = "NC",
                            Street1 = "762 Maple Ave.",
                            ZIP = "28715"
                        },
                        new
                        {
                            CustomerId = 79,
                            City = "Knoxville",
                            Email = "rtorres@mail.net",
                            FirstName = "Ramona",
                            LastName = "Torres",
                            State = "TN",
                            Street1 = "9543 Paxton Dr.",
                            ZIP = "37918"
                        },
                        new
                        {
                            CustomerId = 82,
                            City = "Asheville",
                            Email = "kingkayaker@rockbridge.net",
                            FirstName = "Jackson",
                            LastName = "Beaudoin",
                            State = "NC",
                            Street1 = "781 Houston St.",
                            ZIP = "28732"
                        },
                        new
                        {
                            CustomerId = 86,
                            City = "Gatlinburg",
                            Email = "heinslawrence@rockbridge.net",
                            FirstName = "Lawrence",
                            LastName = "Heins",
                            State = "TN",
                            Street1 = "6134 Slag Ln.",
                            ZIP = "37738"
                        },
                        new
                        {
                            CustomerId = 88,
                            City = "Asheville",
                            Email = "tommyvlexington@mail.com",
                            FirstName = "Thomas",
                            LastName = "Venable",
                            State = "NC",
                            Street1 = "513 Morningside Dr.",
                            ZIP = "28715"
                        },
                        new
                        {
                            CustomerId = 89,
                            City = "Knoxville",
                            Email = "bivinsv88@gmail.com",
                            FirstName = "Victor",
                            LastName = "Bivins",
                            State = "TN",
                            Street1 = "986 Central Rd.",
                            Street2 = "Apt. 211",
                            ZIP = "37918"
                        },
                        new
                        {
                            CustomerId = 92,
                            City = "Knoxville",
                            Email = "leftwichbob19@gmail.com",
                            FirstName = "Bobby",
                            LastName = "Leftwich",
                            State = "TN",
                            Street1 = "1876 McClaughlin St.",
                            ZIP = "37918"
                        },
                        new
                        {
                            CustomerId = 95,
                            City = "Gatlinburg",
                            Email = "musefamily@hotmail.com",
                            FirstName = "Antonio",
                            LastName = "Muse",
                            State = "TN",
                            Street1 = "2136 Rockbridge Way",
                            ZIP = "37738"
                        },
                        new
                        {
                            CustomerId = 97,
                            City = "Knoxville",
                            Email = "bottomsnick12@gmail.com",
                            FirstName = "Nicholas",
                            LastName = "Bottoms",
                            State = "TN",
                            Street1 = "7809 Red Hill Rd.",
                            ZIP = "37918"
                        },
                        new
                        {
                            CustomerId = 98,
                            City = "Murfreesboro",
                            Email = "mendesd@gmail.com",
                            FirstName = "David",
                            LastName = "Mendes",
                            State = "TN",
                            Street1 = "891 Reagan St.",
                            ZIP = "37128"
                        });
                });

            modelBuilder.Entity("MGO_MVC.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Commission")
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1063,
                            Commission = 0.05m,
                            FirstName = "Josh",
                            LastName = "Williams",
                            Position = "Manager"
                        },
                        new
                        {
                            EmployeeId = 1492,
                            Commission = 0.08m,
                            FirstName = "Nathan",
                            LastName = "Bussell",
                            Position = "Buyer/Seller"
                        },
                        new
                        {
                            EmployeeId = 3325,
                            Commission = 0.065m,
                            FirstName = "Brandy",
                            LastName = "Chaffi",
                            Position = "Buyer/Seller"
                        },
                        new
                        {
                            EmployeeId = 5701,
                            Commission = 0.08m,
                            FirstName = "Lori",
                            LastName = "Kish",
                            Position = "Seller"
                        },
                        new
                        {
                            EmployeeId = 6795,
                            Commission = 0.07m,
                            FirstName = "Tony",
                            LastName = "Gregg",
                            Position = "Seller"
                        });
                });

            modelBuilder.Entity("MGO_MVC.Models.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(8,2)");

                    b.HasKey("ItemId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            ItemId = 1299,
                            CategoryId = 410,
                            Cost = 125.00m,
                            Name = "Sierra Designs Pyro 15",
                            Price = 249.95m
                        },
                        new
                        {
                            ItemId = 1318,
                            CategoryId = 729,
                            Cost = 280.00m,
                            Name = "Rossignol Avenger 76 Carbon",
                            Price = 559.96m
                        },
                        new
                        {
                            ItemId = 1327,
                            CategoryId = 477,
                            Cost = 200.00m,
                            Name = "Mountain Safety Research Mutha Hubba",
                            Price = 399.95m
                        },
                        new
                        {
                            ItemId = 1662,
                            CategoryId = 685,
                            Cost = 200.00m,
                            Name = "Lange Concept 9",
                            Price = 399.95m
                        },
                        new
                        {
                            ItemId = 2342,
                            CategoryId = 320,
                            Cost = 465.00m,
                            Name = "GT Ruckus DJ 2.0",
                            Price = 929.00m
                        },
                        new
                        {
                            ItemId = 2395,
                            CategoryId = 477,
                            Cost = 230.00m,
                            Name = "Sierra Designs Lightning XT4",
                            Price = 459.95m
                        },
                        new
                        {
                            ItemId = 3161,
                            CategoryId = 283,
                            Cost = 80.00m,
                            Name = "Mountainsmtih Lookout 45",
                            Price = 159.00m
                        },
                        new
                        {
                            ItemId = 3410,
                            CategoryId = 477,
                            Cost = 225.00m,
                            Name = "Sierra Designs Convert 2",
                            Price = 449.95m
                        },
                        new
                        {
                            ItemId = 3486,
                            CategoryId = 729,
                            Cost = 362.5m,
                            Name = "K2 Shockwave",
                            Price = 725.00m
                        },
                        new
                        {
                            ItemId = 4295,
                            CategoryId = 320,
                            Cost = 2300.00m,
                            Name = "Cannondale Claymore 2",
                            Price = 4599.00m
                        },
                        new
                        {
                            ItemId = 4563,
                            CategoryId = 410,
                            Cost = 185.00m,
                            Name = "The North Face Nebula",
                            Price = 369.00m
                        },
                        new
                        {
                            ItemId = 4706,
                            CategoryId = 477,
                            Cost = 275.00m,
                            Name = "Marmot Thor 3P",
                            Price = 550.00m
                        },
                        new
                        {
                            ItemId = 4809,
                            CategoryId = 283,
                            Cost = 125.00m,
                            Name = "The North Face El Lobo 60",
                            Price = 249.00m
                        },
                        new
                        {
                            ItemId = 4978,
                            CategoryId = 283,
                            Cost = 45.00m,
                            Name = "Kelty Shrike 32",
                            Price = 89.95m
                        },
                        new
                        {
                            ItemId = 5284,
                            CategoryId = 685,
                            Cost = 175.00m,
                            Name = "Salomon Quest 8",
                            Price = 349.99m
                        },
                        new
                        {
                            ItemId = 5909,
                            CategoryId = 477,
                            Cost = 150.00m,
                            Name = "Kelty Buttress 6",
                            Price = 299.95m
                        },
                        new
                        {
                            ItemId = 6195,
                            CategoryId = 685,
                            Cost = 247.5m,
                            Name = "Tecnica USA Agent 80",
                            Price = 495.00m
                        },
                        new
                        {
                            ItemId = 7571,
                            CategoryId = 283,
                            Cost = 60.00m,
                            Name = "Kelty Yukon 48",
                            Price = 119.95m
                        },
                        new
                        {
                            ItemId = 7614,
                            CategoryId = 410,
                            Cost = 210.00m,
                            Name = "Sierra Designs Vapor 15",
                            Price = 419.95m
                        },
                        new
                        {
                            ItemId = 7816,
                            CategoryId = 320,
                            Cost = 1375.00m,
                            Name = "Trek Ticket Signature",
                            Price = 2749.99m
                        },
                        new
                        {
                            ItemId = 7931,
                            CategoryId = 320,
                            Cost = 360.00m,
                            Name = "Specialized Rockhopper",
                            Price = 720.00m
                        },
                        new
                        {
                            ItemId = 8148,
                            CategoryId = 685,
                            Cost = 240.00m,
                            Name = "Rossignol Synergy Sensor 100",
                            Price = 479.95m
                        },
                        new
                        {
                            ItemId = 9034,
                            CategoryId = 410,
                            Cost = 154.50m,
                            Name = "The North Face Dark Star",
                            Price = 309.00m
                        },
                        new
                        {
                            ItemId = 9398,
                            CategoryId = 729,
                            Cost = 300.00m,
                            Name = "Salomon BBR 7.9",
                            Price = 599.95m
                        },
                        new
                        {
                            ItemId = 9887,
                            CategoryId = 283,
                            Cost = 94.50m,
                            Name = "Mountainsmith Apex 75",
                            Price = 189.00m
                        });
                });

            modelBuilder.Entity("MGO_MVC.Models.Purchase", b =>
                {
                    b.Property<int>("PurchaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.HasKey("PurchaseId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Purchases");

                    b.HasData(
                        new
                        {
                            PurchaseId = 2025,
                            EmployeeId = 3325,
                            PurchaseDate = new DateTime(2020, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PurchaseId = 2026,
                            EmployeeId = 3325,
                            PurchaseDate = new DateTime(2020, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PurchaseId = 2027,
                            EmployeeId = 3325,
                            PurchaseDate = new DateTime(2020, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PurchaseId = 2028,
                            EmployeeId = 3325,
                            PurchaseDate = new DateTime(2020, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PurchaseId = 2029,
                            EmployeeId = 3325,
                            PurchaseDate = new DateTime(2020, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PurchaseId = 2030,
                            EmployeeId = 3325,
                            PurchaseDate = new DateTime(2020, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PurchaseId = 2031,
                            EmployeeId = 3325,
                            PurchaseDate = new DateTime(2020, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PurchaseId = 2032,
                            EmployeeId = 3325,
                            PurchaseDate = new DateTime(2020, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PurchaseId = 2033,
                            EmployeeId = 3325,
                            PurchaseDate = new DateTime(2020, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PurchaseId = 2034,
                            EmployeeId = 3325,
                            PurchaseDate = new DateTime(2020, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PurchaseId = 2035,
                            EmployeeId = 3325,
                            PurchaseDate = new DateTime(2020, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PurchaseId = 2036,
                            EmployeeId = 3325,
                            PurchaseDate = new DateTime(2020, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PurchaseId = 2037,
                            EmployeeId = 3325,
                            PurchaseDate = new DateTime(2020, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PurchaseId = 2038,
                            EmployeeId = 3325,
                            PurchaseDate = new DateTime(2020, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PurchaseId = 2039,
                            EmployeeId = 3325,
                            PurchaseDate = new DateTime(2020, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PurchaseId = 2040,
                            EmployeeId = 1492,
                            PurchaseDate = new DateTime(2020, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PurchaseId = 2041,
                            EmployeeId = 1492,
                            PurchaseDate = new DateTime(2020, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PurchaseId = 2042,
                            EmployeeId = 1492,
                            PurchaseDate = new DateTime(2020, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PurchaseId = 2043,
                            EmployeeId = 1492,
                            PurchaseDate = new DateTime(2020, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PurchaseId = 2044,
                            EmployeeId = 1492,
                            PurchaseDate = new DateTime(2020, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("MGO_MVC.Models.PurchaseItem", b =>
                {
                    b.Property<int>("PurchaseId")
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("PurchaseQty")
                        .HasColumnType("int");

                    b.HasKey("PurchaseId", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("PurchaseItems");

                    b.HasData(
                        new
                        {
                            PurchaseId = 2025,
                            ItemId = 3161,
                            PurchaseQty = 3
                        },
                        new
                        {
                            PurchaseId = 2025,
                            ItemId = 9887,
                            PurchaseQty = 10
                        },
                        new
                        {
                            PurchaseId = 2025,
                            ItemId = 1299,
                            PurchaseQty = 2
                        },
                        new
                        {
                            PurchaseId = 2026,
                            ItemId = 2395,
                            PurchaseQty = 4
                        },
                        new
                        {
                            PurchaseId = 2026,
                            ItemId = 3410,
                            PurchaseQty = 3
                        },
                        new
                        {
                            PurchaseId = 2026,
                            ItemId = 7614,
                            PurchaseQty = 3
                        },
                        new
                        {
                            PurchaseId = 2027,
                            ItemId = 4978,
                            PurchaseQty = 3
                        },
                        new
                        {
                            PurchaseId = 2027,
                            ItemId = 5909,
                            PurchaseQty = 3
                        },
                        new
                        {
                            PurchaseId = 2027,
                            ItemId = 7571,
                            PurchaseQty = 3
                        },
                        new
                        {
                            PurchaseId = 2028,
                            ItemId = 6195,
                            PurchaseQty = 5
                        },
                        new
                        {
                            PurchaseId = 2029,
                            ItemId = 1662,
                            PurchaseQty = 5
                        },
                        new
                        {
                            PurchaseId = 2030,
                            ItemId = 1327,
                            PurchaseQty = 3
                        },
                        new
                        {
                            PurchaseId = 2031,
                            ItemId = 4563,
                            PurchaseQty = 3
                        },
                        new
                        {
                            PurchaseId = 2031,
                            ItemId = 4809,
                            PurchaseQty = 3
                        },
                        new
                        {
                            PurchaseId = 2031,
                            ItemId = 9034,
                            PurchaseQty = 3
                        },
                        new
                        {
                            PurchaseId = 2032,
                            ItemId = 4706,
                            PurchaseQty = 4
                        },
                        new
                        {
                            PurchaseId = 2033,
                            ItemId = 1318,
                            PurchaseQty = 2
                        },
                        new
                        {
                            PurchaseId = 2033,
                            ItemId = 8148,
                            PurchaseQty = 4
                        },
                        new
                        {
                            PurchaseId = 2034,
                            ItemId = 3486,
                            PurchaseQty = 6
                        },
                        new
                        {
                            PurchaseId = 2035,
                            ItemId = 5284,
                            PurchaseQty = 2
                        },
                        new
                        {
                            PurchaseId = 2035,
                            ItemId = 9398,
                            PurchaseQty = 2
                        },
                        new
                        {
                            PurchaseId = 2036,
                            ItemId = 4295,
                            PurchaseQty = 3
                        },
                        new
                        {
                            PurchaseId = 2037,
                            ItemId = 2342,
                            PurchaseQty = 3
                        },
                        new
                        {
                            PurchaseId = 2038,
                            ItemId = 7816,
                            PurchaseQty = 4
                        },
                        new
                        {
                            PurchaseId = 2039,
                            ItemId = 7816,
                            PurchaseQty = 6
                        },
                        new
                        {
                            PurchaseId = 2040,
                            ItemId = 2395,
                            PurchaseQty = 3
                        },
                        new
                        {
                            PurchaseId = 2041,
                            ItemId = 6195,
                            PurchaseQty = 3
                        },
                        new
                        {
                            PurchaseId = 2042,
                            ItemId = 4563,
                            PurchaseQty = 3
                        },
                        new
                        {
                            PurchaseId = 2043,
                            ItemId = 3486,
                            PurchaseQty = 10
                        },
                        new
                        {
                            PurchaseId = 2044,
                            ItemId = 3161,
                            PurchaseQty = 3
                        });
                });

            modelBuilder.Entity("MGO_MVC.Models.Sale", b =>
                {
                    b.Property<int>("SaleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SaleDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SaleTime")
                        .HasColumnType("datetime2");

                    b.HasKey("SaleId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Sales");

                    b.HasData(
                        new
                        {
                            SaleId = 1051,
                            CustomerId = 61,
                            EmployeeId = 3325,
                            SaleDate = new DateTime(2020, 10, 4, 20, 30, 0, 0, DateTimeKind.Unspecified),
                            SaleTime = new DateTime(1899, 12, 30, 20, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SaleId = 1052,
                            CustomerId = 64,
                            EmployeeId = 1492,
                            SaleDate = new DateTime(2020, 10, 5, 11, 45, 0, 0, DateTimeKind.Unspecified),
                            SaleTime = new DateTime(1899, 12, 30, 11, 45, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SaleId = 1053,
                            CustomerId = 58,
                            EmployeeId = 1492,
                            SaleDate = new DateTime(2020, 10, 5, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            SaleTime = new DateTime(1899, 12, 30, 18, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SaleId = 1054,
                            CustomerId = 23,
                            EmployeeId = 6795,
                            SaleDate = new DateTime(2020, 10, 6, 12, 30, 0, 0, DateTimeKind.Unspecified),
                            SaleTime = new DateTime(1899, 12, 30, 12, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SaleId = 1055,
                            CustomerId = 61,
                            EmployeeId = 6795,
                            SaleDate = new DateTime(2020, 10, 6, 12, 47, 0, 0, DateTimeKind.Unspecified),
                            SaleTime = new DateTime(1899, 12, 30, 12, 47, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SaleId = 1056,
                            CustomerId = 78,
                            EmployeeId = 3325,
                            SaleDate = new DateTime(2020, 10, 6, 13, 20, 0, 0, DateTimeKind.Unspecified),
                            SaleTime = new DateTime(1899, 12, 30, 13, 20, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SaleId = 1057,
                            CustomerId = 30,
                            EmployeeId = 6795,
                            SaleDate = new DateTime(2020, 10, 7, 13, 15, 0, 0, DateTimeKind.Unspecified),
                            SaleTime = new DateTime(1899, 12, 30, 13, 15, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SaleId = 1058,
                            CustomerId = 69,
                            EmployeeId = 6795,
                            SaleDate = new DateTime(2020, 10, 7, 13, 45, 0, 0, DateTimeKind.Unspecified),
                            SaleTime = new DateTime(1899, 12, 30, 13, 45, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SaleId = 1059,
                            CustomerId = 69,
                            EmployeeId = 6795,
                            SaleDate = new DateTime(2020, 10, 7, 14, 10, 0, 0, DateTimeKind.Unspecified),
                            SaleTime = new DateTime(1899, 12, 30, 14, 10, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SaleId = 1060,
                            CustomerId = 66,
                            EmployeeId = 6795,
                            SaleDate = new DateTime(2020, 10, 7, 17, 38, 0, 0, DateTimeKind.Unspecified),
                            SaleTime = new DateTime(1899, 12, 30, 17, 38, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SaleId = 1061,
                            CustomerId = 40,
                            EmployeeId = 1492,
                            SaleDate = new DateTime(2020, 10, 8, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            SaleTime = new DateTime(1899, 12, 30, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SaleId = 1062,
                            CustomerId = 92,
                            EmployeeId = 6795,
                            SaleDate = new DateTime(2020, 10, 8, 17, 40, 0, 0, DateTimeKind.Unspecified),
                            SaleTime = new DateTime(1899, 12, 30, 17, 40, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SaleId = 1063,
                            CustomerId = 70,
                            EmployeeId = 3325,
                            SaleDate = new DateTime(2020, 10, 11, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            SaleTime = new DateTime(1899, 12, 30, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SaleId = 1064,
                            CustomerId = 88,
                            EmployeeId = 1492,
                            SaleDate = new DateTime(2020, 10, 11, 17, 45, 0, 0, DateTimeKind.Unspecified),
                            SaleTime = new DateTime(1899, 12, 30, 17, 45, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SaleId = 1065,
                            CustomerId = 25,
                            EmployeeId = 3325,
                            SaleDate = new DateTime(2020, 10, 11, 20, 37, 0, 0, DateTimeKind.Unspecified),
                            SaleTime = new DateTime(1899, 12, 30, 20, 37, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SaleId = 1066,
                            CustomerId = 60,
                            EmployeeId = 1492,
                            SaleDate = new DateTime(2020, 10, 12, 13, 15, 0, 0, DateTimeKind.Unspecified),
                            SaleTime = new DateTime(1899, 12, 30, 13, 15, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SaleId = 1067,
                            CustomerId = 89,
                            EmployeeId = 1492,
                            SaleDate = new DateTime(2020, 10, 13, 14, 15, 0, 0, DateTimeKind.Unspecified),
                            SaleTime = new DateTime(1899, 12, 30, 14, 15, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SaleId = 1068,
                            CustomerId = 79,
                            EmployeeId = 3325,
                            SaleDate = new DateTime(2020, 10, 13, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            SaleTime = new DateTime(1899, 12, 30, 19, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SaleId = 1069,
                            CustomerId = 34,
                            EmployeeId = 1492,
                            SaleDate = new DateTime(2020, 10, 13, 19, 15, 0, 0, DateTimeKind.Unspecified),
                            SaleTime = new DateTime(1899, 12, 30, 19, 15, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SaleId = 1070,
                            CustomerId = 15,
                            EmployeeId = 1492,
                            SaleDate = new DateTime(2020, 10, 13, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            SaleTime = new DateTime(1899, 12, 30, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SaleId = 1071,
                            CustomerId = 74,
                            EmployeeId = 5701,
                            SaleDate = new DateTime(2020, 10, 15, 17, 30, 0, 0, DateTimeKind.Unspecified),
                            SaleTime = new DateTime(1899, 12, 30, 17, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SaleId = 1072,
                            CustomerId = 97,
                            EmployeeId = 5701,
                            SaleDate = new DateTime(2020, 10, 15, 18, 45, 0, 0, DateTimeKind.Unspecified),
                            SaleTime = new DateTime(1899, 12, 30, 18, 45, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SaleId = 1073,
                            CustomerId = 36,
                            EmployeeId = 1492,
                            SaleDate = new DateTime(2020, 10, 16, 12, 45, 0, 0, DateTimeKind.Unspecified),
                            SaleTime = new DateTime(1899, 12, 30, 12, 45, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SaleId = 1074,
                            CustomerId = 32,
                            EmployeeId = 1492,
                            SaleDate = new DateTime(2020, 10, 16, 13, 30, 0, 0, DateTimeKind.Unspecified),
                            SaleTime = new DateTime(1899, 12, 30, 13, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SaleId = 1075,
                            CustomerId = 98,
                            EmployeeId = 5701,
                            SaleDate = new DateTime(2020, 10, 16, 15, 15, 0, 0, DateTimeKind.Unspecified),
                            SaleTime = new DateTime(1899, 12, 30, 15, 15, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SaleId = 1076,
                            CustomerId = 13,
                            EmployeeId = 1492,
                            SaleDate = new DateTime(2020, 10, 16, 18, 45, 0, 0, DateTimeKind.Unspecified),
                            SaleTime = new DateTime(1899, 12, 30, 18, 45, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SaleId = 1077,
                            CustomerId = 27,
                            EmployeeId = 1492,
                            SaleDate = new DateTime(2020, 10, 16, 20, 30, 0, 0, DateTimeKind.Unspecified),
                            SaleTime = new DateTime(1899, 12, 30, 20, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SaleId = 1078,
                            CustomerId = 23,
                            EmployeeId = 3325,
                            SaleDate = new DateTime(2020, 10, 17, 13, 10, 0, 0, DateTimeKind.Unspecified),
                            SaleTime = new DateTime(1899, 12, 30, 13, 10, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SaleId = 1079,
                            CustomerId = 82,
                            EmployeeId = 5701,
                            SaleDate = new DateTime(2020, 10, 17, 13, 15, 0, 0, DateTimeKind.Unspecified),
                            SaleTime = new DateTime(1899, 12, 30, 13, 15, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SaleId = 1080,
                            CustomerId = 11,
                            EmployeeId = 3325,
                            SaleDate = new DateTime(2020, 10, 18, 13, 45, 0, 0, DateTimeKind.Unspecified),
                            SaleTime = new DateTime(1899, 12, 30, 13, 45, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SaleId = 1081,
                            CustomerId = 75,
                            EmployeeId = 3325,
                            SaleDate = new DateTime(2020, 10, 18, 19, 38, 0, 0, DateTimeKind.Unspecified),
                            SaleTime = new DateTime(1899, 12, 30, 19, 38, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SaleId = 1082,
                            CustomerId = 92,
                            EmployeeId = 6795,
                            SaleDate = new DateTime(2020, 10, 18, 19, 45, 0, 0, DateTimeKind.Unspecified),
                            SaleTime = new DateTime(1899, 12, 30, 19, 45, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SaleId = 1083,
                            CustomerId = 86,
                            EmployeeId = 3325,
                            SaleDate = new DateTime(2020, 10, 18, 19, 50, 0, 0, DateTimeKind.Unspecified),
                            SaleTime = new DateTime(1899, 12, 30, 19, 50, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SaleId = 1084,
                            CustomerId = 70,
                            EmployeeId = 6795,
                            SaleDate = new DateTime(2020, 10, 18, 19, 55, 0, 0, DateTimeKind.Unspecified),
                            SaleTime = new DateTime(1899, 12, 30, 19, 55, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("MGO_MVC.Models.SaleItem", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("SaleId")
                        .HasColumnType("int");

                    b.Property<int>("SaleQtySold")
                        .HasColumnType("int");

                    b.HasKey("ItemId", "SaleId");

                    b.HasIndex("SaleId");

                    b.ToTable("SaleItems");

                    b.HasData(
                        new
                        {
                            ItemId = 4706,
                            SaleId = 1051,
                            SaleQtySold = 1
                        },
                        new
                        {
                            ItemId = 3486,
                            SaleId = 1052,
                            SaleQtySold = 5
                        },
                        new
                        {
                            ItemId = 6195,
                            SaleId = 1052,
                            SaleQtySold = 2
                        },
                        new
                        {
                            ItemId = 3486,
                            SaleId = 1053,
                            SaleQtySold = 1
                        },
                        new
                        {
                            ItemId = 8148,
                            SaleId = 1053,
                            SaleQtySold = 1
                        },
                        new
                        {
                            ItemId = 2395,
                            SaleId = 1054,
                            SaleQtySold = 1
                        },
                        new
                        {
                            ItemId = 4563,
                            SaleId = 1054,
                            SaleQtySold = 1
                        },
                        new
                        {
                            ItemId = 4809,
                            SaleId = 1054,
                            SaleQtySold = 1
                        },
                        new
                        {
                            ItemId = 3410,
                            SaleId = 1055,
                            SaleQtySold = 1
                        },
                        new
                        {
                            ItemId = 7614,
                            SaleId = 1055,
                            SaleQtySold = 1
                        },
                        new
                        {
                            ItemId = 2342,
                            SaleId = 1056,
                            SaleQtySold = 1
                        },
                        new
                        {
                            ItemId = 1327,
                            SaleId = 1057,
                            SaleQtySold = 1
                        },
                        new
                        {
                            ItemId = 1299,
                            SaleId = 1058,
                            SaleQtySold = 2
                        },
                        new
                        {
                            ItemId = 7571,
                            SaleId = 1058,
                            SaleQtySold = 1
                        },
                        new
                        {
                            ItemId = 6195,
                            SaleId = 1059,
                            SaleQtySold = 1
                        },
                        new
                        {
                            ItemId = 1318,
                            SaleId = 1060,
                            SaleQtySold = 1
                        },
                        new
                        {
                            ItemId = 6195,
                            SaleId = 1060,
                            SaleQtySold = 1
                        },
                        new
                        {
                            ItemId = 2342,
                            SaleId = 1061,
                            SaleQtySold = 1
                        },
                        new
                        {
                            ItemId = 3161,
                            SaleId = 1062,
                            SaleQtySold = 1
                        },
                        new
                        {
                            ItemId = 6195,
                            SaleId = 1063,
                            SaleQtySold = 1
                        },
                        new
                        {
                            ItemId = 9398,
                            SaleId = 1063,
                            SaleQtySold = 1
                        },
                        new
                        {
                            ItemId = 4295,
                            SaleId = 1064,
                            SaleQtySold = 3
                        },
                        new
                        {
                            ItemId = 1662,
                            SaleId = 1065,
                            SaleQtySold = 1
                        },
                        new
                        {
                            ItemId = 8148,
                            SaleId = 1065,
                            SaleQtySold = 1
                        },
                        new
                        {
                            ItemId = 9887,
                            SaleId = 1065,
                            SaleQtySold = 3
                        },
                        new
                        {
                            ItemId = 7816,
                            SaleId = 1066,
                            SaleQtySold = 1
                        },
                        new
                        {
                            ItemId = 7816,
                            SaleId = 1067,
                            SaleQtySold = 2
                        },
                        new
                        {
                            ItemId = 5909,
                            SaleId = 1068,
                            SaleQtySold = 1
                        },
                        new
                        {
                            ItemId = 1662,
                            SaleId = 1069,
                            SaleQtySold = 1
                        },
                        new
                        {
                            ItemId = 2395,
                            SaleId = 1070,
                            SaleQtySold = 1
                        },
                        new
                        {
                            ItemId = 4563,
                            SaleId = 1070,
                            SaleQtySold = 1
                        },
                        new
                        {
                            ItemId = 7816,
                            SaleId = 1071,
                            SaleQtySold = 1
                        },
                        new
                        {
                            ItemId = 2395,
                            SaleId = 1072,
                            SaleQtySold = 1
                        },
                        new
                        {
                            ItemId = 4809,
                            SaleId = 1072,
                            SaleQtySold = 1
                        },
                        new
                        {
                            ItemId = 4809,
                            SaleId = 1073,
                            SaleQtySold = 1
                        },
                        new
                        {
                            ItemId = 1662,
                            SaleId = 1074,
                            SaleQtySold = 1
                        },
                        new
                        {
                            ItemId = 9398,
                            SaleId = 1074,
                            SaleQtySold = 1
                        },
                        new
                        {
                            ItemId = 3161,
                            SaleId = 1075,
                            SaleQtySold = 1
                        },
                        new
                        {
                            ItemId = 4706,
                            SaleId = 1076,
                            SaleQtySold = 1
                        },
                        new
                        {
                            ItemId = 7816,
                            SaleId = 1077,
                            SaleQtySold = 1
                        },
                        new
                        {
                            ItemId = 4978,
                            SaleId = 1078,
                            SaleQtySold = 1
                        },
                        new
                        {
                            ItemId = 5284,
                            SaleId = 1079,
                            SaleQtySold = 1
                        },
                        new
                        {
                            ItemId = 1318,
                            SaleId = 1080,
                            SaleQtySold = 1
                        },
                        new
                        {
                            ItemId = 3486,
                            SaleId = 1080,
                            SaleQtySold = 1
                        },
                        new
                        {
                            ItemId = 9887,
                            SaleId = 1080,
                            SaleQtySold = 1
                        },
                        new
                        {
                            ItemId = 9887,
                            SaleId = 1081,
                            SaleQtySold = 2
                        },
                        new
                        {
                            ItemId = 3161,
                            SaleId = 1082,
                            SaleQtySold = 1
                        },
                        new
                        {
                            ItemId = 1318,
                            SaleId = 1083,
                            SaleQtySold = 1
                        },
                        new
                        {
                            ItemId = 3486,
                            SaleId = 1083,
                            SaleQtySold = 1
                        },
                        new
                        {
                            ItemId = 5284,
                            SaleId = 1083,
                            SaleQtySold = 1
                        },
                        new
                        {
                            ItemId = 9034,
                            SaleId = 1083,
                            SaleQtySold = 1
                        },
                        new
                        {
                            ItemId = 3486,
                            SaleId = 1084,
                            SaleQtySold = 3
                        });
                });

            modelBuilder.Entity("MGO_MVC.Models.Item", b =>
                {
                    b.HasOne("MGO_MVC.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MGO_MVC.Models.Purchase", b =>
                {
                    b.HasOne("MGO_MVC.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("MGO_MVC.Models.PurchaseItem", b =>
                {
                    b.HasOne("MGO_MVC.Models.Item", "Item")
                        .WithMany("PurchaseItems")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MGO_MVC.Models.Purchase", "Purchase")
                        .WithMany("PurchaseItems")
                        .HasForeignKey("PurchaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Purchase");
                });

            modelBuilder.Entity("MGO_MVC.Models.Sale", b =>
                {
                    b.HasOne("MGO_MVC.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MGO_MVC.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("MGO_MVC.Models.SaleItem", b =>
                {
                    b.HasOne("MGO_MVC.Models.Item", "Item")
                        .WithMany("SaleItems")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MGO_MVC.Models.Sale", "Sale")
                        .WithMany("SaleItems")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("MGO_MVC.Models.Item", b =>
                {
                    b.Navigation("PurchaseItems");

                    b.Navigation("SaleItems");
                });

            modelBuilder.Entity("MGO_MVC.Models.Purchase", b =>
                {
                    b.Navigation("PurchaseItems");
                });

            modelBuilder.Entity("MGO_MVC.Models.Sale", b =>
                {
                    b.Navigation("SaleItems");
                });
#pragma warning restore 612, 618
        }
    }
}
